language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"

install:
    - python setup.py install
    - pip install -r requirements_test.txt

script:
  - pep8 --ignore=E501 *.py test/*.py
  - pylint --rcfile=pylint.rc *.py test/*.py
  - pyflakes *.py test/*.py
  - nosetests test/

